name: CoderCo Custom Action CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: checkout code
      run: actions/checkout@v2

    - name: Hello world custom action
      uses: ayubfarahh/coderco-custom@main
      with:
        who-to-greet: 'Coderco Team'

