name: CoderCo Secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: checkout Code
      uses: actions/checkout@v2


    - name: use Secrets
      run: echo "The secret is ${{ secret.MY_SECRET }}"